### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Pex77** [RozhakXD/Premium#13]
![Screenshot_2024-12-21-22-43-25-032_com termux](https://github.com/user-attachments/assets/b41c181b-7862-434c-9c46-7c0f5eaf2e0b)

apa ini mesti menggunakan koneksi pribadi min ? (tidak boleh terhubung ke hotspot)

**Comment by RozhakDev** [comment]
Yes, WiFi can affect the results, so we do not allow users to use WiFi networks!

![WIFi Blocked](https://github.com/user-attachments/assets/ef5fd6fd-000e-4cef-89ae-505f6e0c1f51)
